### ISSUE TITLE
Error 126 from hook script on deployment

### ISSUE THREAD

**Issue by tevert** [datagridsys/skopos-sample-app#3]
Running Windows 10 (Build 14393), Docker 17.03.1-ce-win12 (12058)

I've progressed through the README up to "Run deploy", and get this: [screenshot](http://imgur.com/a/JwRby)

Error 126 is a bash error for 'cannot execute', and usually indicates a permission issue.

Things I've already checked: 
* The script file is executable
* Tried removing the shebang, no change
* Tried executing the script on the skopos container via 'docker exec', ran fine

What other details should I provide?

**Comment by 30blows** [comment]
Hi Tyler -

I reproduced this issue.  The problem derives from git clone by default changing the line endings of fetched files to match the local environment (windows in this case), so that the skopos-sample-app script line endings are CRLF (windows) instead of LF (unix).  We will fix this by adding a .gitattributes file to the repo to prevent this behavior in the future.

Meanwhile, you can proceed by fixing this problem in your local clone of the skopos-sample-app:

- from a cloned repo directory execute “git config --local core.autocrlf false” to disable line-ending fix-up for this local clone on fetch
- “git fetch --all” to download the repo files again without trying to merge/rebase
- “git reset --hard origin/master” to change all the files in the local working tree to match the files in origin/master

That should fix-up your local copy so you can proceed.

Thanks -
Stephen Quintero

**Comment by tevert** [comment]
Yep, that did the trick. Thanks!
